<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Hangfire" />
		<PackageReference Include="Hangfire.PostgreSql" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
		<PackageReference Include="Stripe.net" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="ArchitectureTests" />
	</ItemGroup>

</Project>
